// Profile components - extracted from Profile.jsx and UserProfile.jsx
export { HeroIdentityCard } from './HeroIdentityCard'
export { FoodMap } from './FoodMap'
export { ShelfFilter } from './ShelfFilter'
export { RecentVisitsList } from './RecentVisitsList'
export { LocalListCard } from './LocalListCard'
export { DeleteAccountModal } from './DeleteAccountSection'
export { CuratorOnboardingSplash } from './CuratorOnboardingSplash'
export { CuratorChecklist } from './CuratorChecklist'
export { ProfileGrid } from './ProfileGrid'
